// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protos/server_v1.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerRequest) Reset() {
	*x = ServerRequest{}
	mi := &file_protos_server_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRequest) ProtoMessage() {}

func (x *ServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_server_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRequest.ProtoReflect.Descriptor instead.
func (*ServerRequest) Descriptor() ([]byte, []int) {
	return file_protos_server_v1_proto_rawDescGZIP(), []int{0}
}

type LoadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoadScore     float64                `protobuf:"fixed64,1,opt,name=load_score,json=loadScore,proto3" json:"load_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadResponse) Reset() {
	*x = LoadResponse{}
	mi := &file_protos_server_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadResponse) ProtoMessage() {}

func (x *LoadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_server_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadResponse.ProtoReflect.Descriptor instead.
func (*LoadResponse) Descriptor() ([]byte, []int) {
	return file_protos_server_v1_proto_rawDescGZIP(), []int{1}
}

func (x *LoadResponse) GetLoadScore() float64 {
	if x != nil {
		return x.LoadScore
	}
	return 0
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_protos_server_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_server_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_protos_server_v1_proto_rawDescGZIP(), []int{2}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_protos_server_v1_proto protoreflect.FileDescriptor

const file_protos_server_v1_proto_rawDesc = "" +
	"\n" +
	"\x16protos/server_v1.proto\x12\tserver.v1\"\x0f\n" +
	"\rServerRequest\"-\n" +
	"\fLoadResponse\x12\x1d\n" +
	"\n" +
	"load_score\x18\x01 \x01(\x01R\tloadScore\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x93\x01\n" +
	"\rServerService\x12>\n" +
	"\aGetLoad\x12\x18.server.v1.ServerRequest\x1a\x17.server.v1.LoadResponse\"\x00\x12B\n" +
	"\tGetHealth\x12\x18.server.v1.ServerRequest\x1a\x19.server.v1.HealthResponse\"\x00B\x0fZ\rpkg/server/v1b\x06proto3"

var (
	file_protos_server_v1_proto_rawDescOnce sync.Once
	file_protos_server_v1_proto_rawDescData []byte
)

func file_protos_server_v1_proto_rawDescGZIP() []byte {
	file_protos_server_v1_proto_rawDescOnce.Do(func() {
		file_protos_server_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_server_v1_proto_rawDesc), len(file_protos_server_v1_proto_rawDesc)))
	})
	return file_protos_server_v1_proto_rawDescData
}

var file_protos_server_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_server_v1_proto_goTypes = []any{
	(*ServerRequest)(nil),  // 0: server.v1.ServerRequest
	(*LoadResponse)(nil),   // 1: server.v1.LoadResponse
	(*HealthResponse)(nil), // 2: server.v1.HealthResponse
}
var file_protos_server_v1_proto_depIdxs = []int32{
	0, // 0: server.v1.ServerService.GetLoad:input_type -> server.v1.ServerRequest
	0, // 1: server.v1.ServerService.GetHealth:input_type -> server.v1.ServerRequest
	1, // 2: server.v1.ServerService.GetLoad:output_type -> server.v1.LoadResponse
	2, // 3: server.v1.ServerService.GetHealth:output_type -> server.v1.HealthResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_server_v1_proto_init() }
func file_protos_server_v1_proto_init() {
	if File_protos_server_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_server_v1_proto_rawDesc), len(file_protos_server_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_server_v1_proto_goTypes,
		DependencyIndexes: file_protos_server_v1_proto_depIdxs,
		MessageInfos:      file_protos_server_v1_proto_msgTypes,
	}.Build()
	File_protos_server_v1_proto = out.File
	file_protos_server_v1_proto_goTypes = nil
	file_protos_server_v1_proto_depIdxs = nil
}
