// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protos/client_v1.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Requests and Responses
type ClientExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientExistsRequest) Reset() {
	*x = ClientExistsRequest{}
	mi := &file_protos_client_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientExistsRequest) ProtoMessage() {}

func (x *ClientExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_client_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientExistsRequest.ProtoReflect.Descriptor instead.
func (*ClientExistsRequest) Descriptor() ([]byte, []int) {
	return file_protos_client_v1_proto_rawDescGZIP(), []int{0}
}

func (x *ClientExistsRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type ClientExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientExistsResponse) Reset() {
	*x = ClientExistsResponse{}
	mi := &file_protos_client_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientExistsResponse) ProtoMessage() {}

func (x *ClientExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_client_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientExistsResponse.ProtoReflect.Descriptor instead.
func (*ClientExistsResponse) Descriptor() ([]byte, []int) {
	return file_protos_client_v1_proto_rawDescGZIP(), []int{1}
}

func (x *ClientExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type GetClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientRequest) Reset() {
	*x = GetClientRequest{}
	mi := &file_protos_client_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientRequest) ProtoMessage() {}

func (x *GetClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_client_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientRequest.ProtoReflect.Descriptor instead.
func (*GetClientRequest) Descriptor() ([]byte, []int) {
	return file_protos_client_v1_proto_rawDescGZIP(), []int{2}
}

func (x *GetClientRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type ClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        *Client                `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientResponse) Reset() {
	*x = ClientResponse{}
	mi := &file_protos_client_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientResponse) ProtoMessage() {}

func (x *ClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_client_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientResponse.ProtoReflect.Descriptor instead.
func (*ClientResponse) Descriptor() ([]byte, []int) {
	return file_protos_client_v1_proto_rawDescGZIP(), []int{3}
}

func (x *ClientResponse) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

type ListClientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clients       []*Client              `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientsResponse) Reset() {
	*x = ListClientsResponse{}
	mi := &file_protos_client_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsResponse) ProtoMessage() {}

func (x *ListClientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_client_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientsResponse.ProtoReflect.Descriptor instead.
func (*ListClientsResponse) Descriptor() ([]byte, []int) {
	return file_protos_client_v1_proto_rawDescGZIP(), []int{4}
}

func (x *ListClientsResponse) GetClients() []*Client {
	if x != nil {
		return x.Clients
	}
	return nil
}

type CreateClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClientRequest) Reset() {
	*x = CreateClientRequest{}
	mi := &file_protos_client_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientRequest) ProtoMessage() {}

func (x *CreateClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_client_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientRequest.ProtoReflect.Descriptor instead.
func (*CreateClientRequest) Descriptor() ([]byte, []int) {
	return file_protos_client_v1_proto_rawDescGZIP(), []int{5}
}

func (x *CreateClientRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *CreateClientRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateClientRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type UpdateClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClientRequest) Reset() {
	*x = UpdateClientRequest{}
	mi := &file_protos_client_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientRequest) ProtoMessage() {}

func (x *UpdateClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_client_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientRequest.ProtoReflect.Descriptor instead.
func (*UpdateClientRequest) Descriptor() ([]byte, []int) {
	return file_protos_client_v1_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateClientRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdateClientRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type DeleteClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClientRequest) Reset() {
	*x = DeleteClientRequest{}
	mi := &file_protos_client_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClientRequest) ProtoMessage() {}

func (x *DeleteClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_client_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClientRequest.ProtoReflect.Descriptor instead.
func (*DeleteClientRequest) Descriptor() ([]byte, []int) {
	return file_protos_client_v1_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteClientRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// Status messages
type GetClientStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientStatusRequest) Reset() {
	*x = GetClientStatusRequest{}
	mi := &file_protos_client_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientStatusRequest) ProtoMessage() {}

func (x *GetClientStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_client_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientStatusRequest.ProtoReflect.Descriptor instead.
func (*GetClientStatusRequest) Descriptor() ([]byte, []int) {
	return file_protos_client_v1_proto_rawDescGZIP(), []int{8}
}

func (x *GetClientStatusRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type ClientStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Online        bool                   `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientStatusResponse) Reset() {
	*x = ClientStatusResponse{}
	mi := &file_protos_client_v1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStatusResponse) ProtoMessage() {}

func (x *ClientStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_client_v1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStatusResponse.ProtoReflect.Descriptor instead.
func (*ClientStatusResponse) Descriptor() ([]byte, []int) {
	return file_protos_client_v1_proto_rawDescGZIP(), []int{9}
}

func (x *ClientStatusResponse) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

type ListClientsStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*ClientStatus        `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientsStatusResponse) Reset() {
	*x = ListClientsStatusResponse{}
	mi := &file_protos_client_v1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientsStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsStatusResponse) ProtoMessage() {}

func (x *ListClientsStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_client_v1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientsStatusResponse.ProtoReflect.Descriptor instead.
func (*ListClientsStatusResponse) Descriptor() ([]byte, []int) {
	return file_protos_client_v1_proto_rawDescGZIP(), []int{10}
}

func (x *ListClientsStatusResponse) GetStatuses() []*ClientStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

// Traffic messages
type GetClientTrafficRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientTrafficRequest) Reset() {
	*x = GetClientTrafficRequest{}
	mi := &file_protos_client_v1_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientTrafficRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientTrafficRequest) ProtoMessage() {}

func (x *GetClientTrafficRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_client_v1_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientTrafficRequest.ProtoReflect.Descriptor instead.
func (*GetClientTrafficRequest) Descriptor() ([]byte, []int) {
	return file_protos_client_v1_proto_rawDescGZIP(), []int{11}
}

func (x *GetClientTrafficRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type ClientTrafficResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Traffic       *Traffic               `protobuf:"bytes,1,opt,name=traffic,proto3" json:"traffic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientTrafficResponse) Reset() {
	*x = ClientTrafficResponse{}
	mi := &file_protos_client_v1_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientTrafficResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTrafficResponse) ProtoMessage() {}

func (x *ClientTrafficResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_client_v1_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTrafficResponse.ProtoReflect.Descriptor instead.
func (*ClientTrafficResponse) Descriptor() ([]byte, []int) {
	return file_protos_client_v1_proto_rawDescGZIP(), []int{12}
}

func (x *ClientTrafficResponse) GetTraffic() *Traffic {
	if x != nil {
		return x.Traffic
	}
	return nil
}

type ListClientsTrafficResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientTraffics []*ClientTraffic       `protobuf:"bytes,1,rep,name=client_traffics,json=clientTraffics,proto3" json:"client_traffics,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListClientsTrafficResponse) Reset() {
	*x = ListClientsTrafficResponse{}
	mi := &file_protos_client_v1_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientsTrafficResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsTrafficResponse) ProtoMessage() {}

func (x *ListClientsTrafficResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_client_v1_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientsTrafficResponse.ProtoReflect.Descriptor instead.
func (*ListClientsTrafficResponse) Descriptor() ([]byte, []int) {
	return file_protos_client_v1_proto_rawDescGZIP(), []int{13}
}

func (x *ListClientsTrafficResponse) GetClientTraffics() []*ClientTraffic {
	if x != nil {
		return x.ClientTraffics
	}
	return nil
}

// Data models
type Client struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Id            uint64                 `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_protos_client_v1_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_protos_client_v1_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_protos_client_v1_proto_rawDescGZIP(), []int{14}
}

func (x *Client) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Client) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Client) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Client) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Traffic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uplink        uint64                 `protobuf:"varint,1,opt,name=uplink,proto3" json:"uplink,omitempty"`
	Downlink      uint64                 `protobuf:"varint,2,opt,name=downlink,proto3" json:"downlink,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Traffic) Reset() {
	*x = Traffic{}
	mi := &file_protos_client_v1_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Traffic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Traffic) ProtoMessage() {}

func (x *Traffic) ProtoReflect() protoreflect.Message {
	mi := &file_protos_client_v1_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Traffic.ProtoReflect.Descriptor instead.
func (*Traffic) Descriptor() ([]byte, []int) {
	return file_protos_client_v1_proto_rawDescGZIP(), []int{15}
}

func (x *Traffic) GetUplink() uint64 {
	if x != nil {
		return x.Uplink
	}
	return 0
}

func (x *Traffic) GetDownlink() uint64 {
	if x != nil {
		return x.Downlink
	}
	return 0
}

func (x *Traffic) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

type ClientTraffic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Traffic       *Traffic               `protobuf:"bytes,3,opt,name=traffic,proto3" json:"traffic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientTraffic) Reset() {
	*x = ClientTraffic{}
	mi := &file_protos_client_v1_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientTraffic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTraffic) ProtoMessage() {}

func (x *ClientTraffic) ProtoReflect() protoreflect.Message {
	mi := &file_protos_client_v1_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTraffic.ProtoReflect.Descriptor instead.
func (*ClientTraffic) Descriptor() ([]byte, []int) {
	return file_protos_client_v1_proto_rawDescGZIP(), []int{16}
}

func (x *ClientTraffic) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ClientTraffic) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ClientTraffic) GetTraffic() *Traffic {
	if x != nil {
		return x.Traffic
	}
	return nil
}

type ClientStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Online        bool                   `protobuf:"varint,3,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientStatus) Reset() {
	*x = ClientStatus{}
	mi := &file_protos_client_v1_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStatus) ProtoMessage() {}

func (x *ClientStatus) ProtoReflect() protoreflect.Message {
	mi := &file_protos_client_v1_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStatus.ProtoReflect.Descriptor instead.
func (*ClientStatus) Descriptor() ([]byte, []int) {
	return file_protos_client_v1_proto_rawDescGZIP(), []int{17}
}

func (x *ClientStatus) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ClientStatus) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ClientStatus) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

var File_protos_client_v1_proto protoreflect.FileDescriptor

const file_protos_client_v1_proto_rawDesc = "" +
	"\n" +
	"\x16protos/client_v1.proto\x12\tclient.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\")\n" +
	"\x13ClientExistsRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\".\n" +
	"\x14ClientExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"&\n" +
	"\x10GetClientRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\";\n" +
	"\x0eClientResponse\x12)\n" +
	"\x06client\x18\x01 \x01(\v2\x11.client.v1.ClientR\x06client\"B\n" +
	"\x13ListClientsResponse\x12+\n" +
	"\aclients\x18\x01 \x03(\v2\x11.client.v1.ClientR\aclients\"z\n" +
	"\x13CreateClientRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"d\n" +
	"\x13UpdateClientRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\")\n" +
	"\x13DeleteClientRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\",\n" +
	"\x16GetClientStatusRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\".\n" +
	"\x14ClientStatusResponse\x12\x16\n" +
	"\x06online\x18\x01 \x01(\bR\x06online\"P\n" +
	"\x19ListClientsStatusResponse\x123\n" +
	"\bstatuses\x18\x01 \x03(\v2\x17.client.v1.ClientStatusR\bstatuses\"-\n" +
	"\x17GetClientTrafficRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"E\n" +
	"\x15ClientTrafficResponse\x12,\n" +
	"\atraffic\x18\x01 \x01(\v2\x12.client.v1.TrafficR\atraffic\"_\n" +
	"\x1aListClientsTrafficResponse\x12A\n" +
	"\x0fclient_traffics\x18\x01 \x03(\v2\x18.client.v1.ClientTrafficR\x0eclientTraffics\"}\n" +
	"\x06Client\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x04R\x02id\"|\n" +
	"\aTraffic\x12\x16\n" +
	"\x06uplink\x18\x01 \x01(\x04R\x06uplink\x12\x1a\n" +
	"\bdownlink\x18\x02 \x01(\x04R\bdownlink\x12=\n" +
	"\flast_updated\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\"g\n" +
	"\rClientTraffic\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12,\n" +
	"\atraffic\x18\x03 \x01(\v2\x12.client.v1.TrafficR\atraffic\"P\n" +
	"\fClientStatus\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x16\n" +
	"\x06online\x18\x03 \x01(\bR\x06online2\xa3\x06\n" +
	"\rClientService\x12O\n" +
	"\fClientExists\x12\x1e.client.v1.ClientExistsRequest\x1a\x1f.client.v1.ClientExistsResponse\x12C\n" +
	"\tGetClient\x12\x1b.client.v1.GetClientRequest\x1a\x19.client.v1.ClientResponse\x12E\n" +
	"\vListClients\x12\x16.google.protobuf.Empty\x1a\x1e.client.v1.ListClientsResponse\x12I\n" +
	"\fCreateClient\x12\x1e.client.v1.CreateClientRequest\x1a\x19.client.v1.ClientResponse\x12I\n" +
	"\fUpdateClient\x12\x1e.client.v1.UpdateClientRequest\x1a\x19.client.v1.ClientResponse\x12F\n" +
	"\fDeleteClient\x12\x1e.client.v1.DeleteClientRequest\x1a\x16.google.protobuf.Empty\x12U\n" +
	"\x0fGetClientStatus\x12!.client.v1.GetClientStatusRequest\x1a\x1f.client.v1.ClientStatusResponse\x12Q\n" +
	"\x11ListClientsStatus\x12\x16.google.protobuf.Empty\x1a$.client.v1.ListClientsStatusResponse\x12X\n" +
	"\x10GetClientTraffic\x12\".client.v1.GetClientTrafficRequest\x1a .client.v1.ClientTrafficResponse\x12S\n" +
	"\x12ListClientsTraffic\x12\x16.google.protobuf.Empty\x1a%.client.v1.ListClientsTrafficResponseB\x0fZ\rpkg/client/v1b\x06proto3"

var (
	file_protos_client_v1_proto_rawDescOnce sync.Once
	file_protos_client_v1_proto_rawDescData []byte
)

func file_protos_client_v1_proto_rawDescGZIP() []byte {
	file_protos_client_v1_proto_rawDescOnce.Do(func() {
		file_protos_client_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_client_v1_proto_rawDesc), len(file_protos_client_v1_proto_rawDesc)))
	})
	return file_protos_client_v1_proto_rawDescData
}

var file_protos_client_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_protos_client_v1_proto_goTypes = []any{
	(*ClientExistsRequest)(nil),        // 0: client.v1.ClientExistsRequest
	(*ClientExistsResponse)(nil),       // 1: client.v1.ClientExistsResponse
	(*GetClientRequest)(nil),           // 2: client.v1.GetClientRequest
	(*ClientResponse)(nil),             // 3: client.v1.ClientResponse
	(*ListClientsResponse)(nil),        // 4: client.v1.ListClientsResponse
	(*CreateClientRequest)(nil),        // 5: client.v1.CreateClientRequest
	(*UpdateClientRequest)(nil),        // 6: client.v1.UpdateClientRequest
	(*DeleteClientRequest)(nil),        // 7: client.v1.DeleteClientRequest
	(*GetClientStatusRequest)(nil),     // 8: client.v1.GetClientStatusRequest
	(*ClientStatusResponse)(nil),       // 9: client.v1.ClientStatusResponse
	(*ListClientsStatusResponse)(nil),  // 10: client.v1.ListClientsStatusResponse
	(*GetClientTrafficRequest)(nil),    // 11: client.v1.GetClientTrafficRequest
	(*ClientTrafficResponse)(nil),      // 12: client.v1.ClientTrafficResponse
	(*ListClientsTrafficResponse)(nil), // 13: client.v1.ListClientsTrafficResponse
	(*Client)(nil),                     // 14: client.v1.Client
	(*Traffic)(nil),                    // 15: client.v1.Traffic
	(*ClientTraffic)(nil),              // 16: client.v1.ClientTraffic
	(*ClientStatus)(nil),               // 17: client.v1.ClientStatus
	(*timestamppb.Timestamp)(nil),      // 18: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 19: google.protobuf.Empty
}
var file_protos_client_v1_proto_depIdxs = []int32{
	14, // 0: client.v1.ClientResponse.client:type_name -> client.v1.Client
	14, // 1: client.v1.ListClientsResponse.clients:type_name -> client.v1.Client
	18, // 2: client.v1.CreateClientRequest.expires_at:type_name -> google.protobuf.Timestamp
	18, // 3: client.v1.UpdateClientRequest.expires_at:type_name -> google.protobuf.Timestamp
	17, // 4: client.v1.ListClientsStatusResponse.statuses:type_name -> client.v1.ClientStatus
	15, // 5: client.v1.ClientTrafficResponse.traffic:type_name -> client.v1.Traffic
	16, // 6: client.v1.ListClientsTrafficResponse.client_traffics:type_name -> client.v1.ClientTraffic
	18, // 7: client.v1.Client.expires_at:type_name -> google.protobuf.Timestamp
	18, // 8: client.v1.Traffic.last_updated:type_name -> google.protobuf.Timestamp
	15, // 9: client.v1.ClientTraffic.traffic:type_name -> client.v1.Traffic
	0,  // 10: client.v1.ClientService.ClientExists:input_type -> client.v1.ClientExistsRequest
	2,  // 11: client.v1.ClientService.GetClient:input_type -> client.v1.GetClientRequest
	19, // 12: client.v1.ClientService.ListClients:input_type -> google.protobuf.Empty
	5,  // 13: client.v1.ClientService.CreateClient:input_type -> client.v1.CreateClientRequest
	6,  // 14: client.v1.ClientService.UpdateClient:input_type -> client.v1.UpdateClientRequest
	7,  // 15: client.v1.ClientService.DeleteClient:input_type -> client.v1.DeleteClientRequest
	8,  // 16: client.v1.ClientService.GetClientStatus:input_type -> client.v1.GetClientStatusRequest
	19, // 17: client.v1.ClientService.ListClientsStatus:input_type -> google.protobuf.Empty
	11, // 18: client.v1.ClientService.GetClientTraffic:input_type -> client.v1.GetClientTrafficRequest
	19, // 19: client.v1.ClientService.ListClientsTraffic:input_type -> google.protobuf.Empty
	1,  // 20: client.v1.ClientService.ClientExists:output_type -> client.v1.ClientExistsResponse
	3,  // 21: client.v1.ClientService.GetClient:output_type -> client.v1.ClientResponse
	4,  // 22: client.v1.ClientService.ListClients:output_type -> client.v1.ListClientsResponse
	3,  // 23: client.v1.ClientService.CreateClient:output_type -> client.v1.ClientResponse
	3,  // 24: client.v1.ClientService.UpdateClient:output_type -> client.v1.ClientResponse
	19, // 25: client.v1.ClientService.DeleteClient:output_type -> google.protobuf.Empty
	9,  // 26: client.v1.ClientService.GetClientStatus:output_type -> client.v1.ClientStatusResponse
	10, // 27: client.v1.ClientService.ListClientsStatus:output_type -> client.v1.ListClientsStatusResponse
	12, // 28: client.v1.ClientService.GetClientTraffic:output_type -> client.v1.ClientTrafficResponse
	13, // 29: client.v1.ClientService.ListClientsTraffic:output_type -> client.v1.ListClientsTrafficResponse
	20, // [20:30] is the sub-list for method output_type
	10, // [10:20] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_protos_client_v1_proto_init() }
func file_protos_client_v1_proto_init() {
	if File_protos_client_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_client_v1_proto_rawDesc), len(file_protos_client_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_client_v1_proto_goTypes,
		DependencyIndexes: file_protos_client_v1_proto_depIdxs,
		MessageInfos:      file_protos_client_v1_proto_msgTypes,
	}.Build()
	File_protos_client_v1_proto = out.File
	file_protos_client_v1_proto_goTypes = nil
	file_protos_client_v1_proto_depIdxs = nil
}
